<%@ Page Title="" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="IPAdmin.aspx.cs" Inherits="InterProduct.IPAdmin" %>

<asp:Content ID="Content1" ContentPlaceHolderID="body" runat="server">
    <form id="form1" runat="server">

         <div class="row">
            <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="x_panel col-md-9">
                    <div class="x_title">
                        <h2>Artikel toevoegen</h2>
                        <div class="clearfix"></div>
                    </div>
                    <div class="x_content col-md-9">
                        <br />
                        <div class="row">
                            <div class="col-md-4">
                                <label class="control-label">Naam</label>
                                <asp:TextBox ID="Naam" class="form-control" runat="server"></asp:TextBox>
                            </div>
                            <div class="col-md-4">
                                <label class="control-label">Prijs</label>
                                <asp:TextBox ID="Prijs" class="form-control" runat="server"></asp:TextBox>
                            </div>
                        </div>
                        <br />
                        <div class="row col-md-8">
                            <asp:Button ID="btnVoegtoe" class="btn btn-success pull-left"  runat="server" Text="Voeg Toe" ></asp:Button>
                        </div>
                    </div>
                </div>
            </div>
        <div>
            <asp:GridView ID="GridView1" CssClass="mydatagrid" PagerStyle-CssClass="pager" HeaderStyle-CssClass="header"
                RowStyle-CssClass="rows" runat="server" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True"
                DataKeyNames="Id" OnRowCancelingEdit="GridView1_RowCancelingEdit" OnRowEditing="GridView1_RowEditing"
                OnRowUpdating="GridView1_RowUpdating" OnRowDeleting="GridView1_RowDeleting">
                <Columns>
                        <asp:TemplateField HeaderText="Naam">
                            <ItemTemplate><%#Eval("Naam")%> </ItemTemplate>
                        </asp:TemplateField>

                        <asp:TemplateField HeaderText="Naam">
                            <ItemTemplate> <%#Eval("Prijs")%> </ItemTemplate>
                            <FooterTemplate>
                                <asp:TextBox ID="tbBook" Width="200px" CssClass="textbox" runat="server" />
                            </FooterTemplate>
                        </asp:TemplateField>
                    </Columns>
            </asp:GridView>
            <style>
                .mydatagrid {
                    width: 80%;
                    border: solid 2px black;
                    min-width: 80%;
                    max-width: 100%;
                }

                .header {
                    background-color: #646464;
                    font-family: Arial;
                    color: White;
                    border: none 0px transparent;
                    height: 25px;
                    text-align: center;
                    font-size: 16px;
                }

                .rows {
                    background-color: #fff;
                    font-family: Arial;
                    font-size: 14px;
                    color: #000;
                    min-height: 25px;
                    text-align: left;
                    border: none 0px transparent;
                }

                    .rows:hover {
                        background-color: #ff8000;
                        font-family: Arial;
                        color: #fff;
                        text-align: left;
                    }

                .selectedrow {
                    background-color: #ff8000;
                    font-family: Arial;
                    color: #fff;
                    font-weight: bold;
                    text-align: left;
                }

                .mydatagrid a /** FOR THE PAGING ICONS  **/ {
                    background-color: Transparent;
                    padding: 5px 5px 5px 5px;
                    color: #fff;
                    text-decoration: none;
                    font-weight: bold;
                }

                    .mydatagrid a:hover /** FOR THE PAGING ICONS  HOVER STYLES**/ {
                        background-color: #000;
                        color: #fff;
                    }

                .mydatagrid span /** FOR THE PAGING ICONS CURRENT PAGE INDICATOR **/ {
                    background-color: #c9c9c9;
                    color: #000;
                    padding: 5px 5px 5px 5px;
                }

                .pager {
                    background-color: #646464;
                    font-family: Arial;
                    color: White;
                    height: 30px;
                    text-align: left;
                }

                .mydatagrid td {
                    padding: 5px;
                }

                .mydatagrid th {
                    padding: 5px;
                }
            </style>
        </div>
    </form>
</asp:Content>
